#!/usr/bin/env ruby

require 'eventmachine'
require 'amqp'
require 'yaml'
require 'json'

# Simulate an Invoca AMQP publisher endpoint
# i.e., publish events to our broker over AMQP

EventMachine.run do
  config = YAML.load_file("../config.yml")
  username = config['rabbitmq']['username']
  password = config['rabbitmq']['password']
  host     = config['rabbitmq']['host']
  port     = config['rabbitmq']['port']
  puts "connecting to amqp://#{username}:#{password}@#{host}:#{port}"

  connection = AMQP.connect("amqp://#{username}:#{password}@#{host}:#{port}")

  channel = AMQP::Channel.new(connection)
  ex = channel.default_exchange

  json = JSON.dump({
    type: "call_start",
    call: { id: "677ee3e5-24d6-43aa-9802-bca05093aed4" }
  })

  puts "Publishing call..."
  ex.publish("test", :routing_key => "invoca_to_broker")

  puts "Done."
end
